### ISSUE TITLE
No tables found on DB2 z/OS

### ISSUE THREAD

**Issue by cabo40** [alisonrafael/metabase-db2-driver#4]
Hi @alisonrafael , thank you very much for this driver.
I can do native queries to the database, but the schema is not updated (not even when manually syncing it).
I've checked the code for other drivers but I have no clue as to why the default call to the driver's method `.getTables` fail.
Maybe by overloading the methods `driver/describe-database` and `driver/describe-table` but I have no clue as of how to implement them.
Do you know what direction can I follow to get the database schema updated so that the tables get listed?

**Comment by alisonrafael** [comment]
Hi @cabo40 ! 
I'm not expertise here, I only did changes in dates and limit/offset because the driver differences in v7r1 iSeries vs. LUW. 
Did you change for the correct driver in the project.clj's dependencies? Did you try anothers project forks? If you really need to override some methods, try to see similar changes in other metabase drivers for another db, it's was what I did, and unfortunally I do not know much more than this yet.
